# .gitpod.yml
image:
  file: .devcontainer/Dockerfile
  context: .devcontainer  # Set context to the folder containing the Dockerfile

tasks:
  - name: Setup
    init: |
      # Add commands to run once during workspace preparation
      # e.g., npm install or pip install
    command: |
      # Add commands to run every time the workspace starts
      echo "Welcome to your AWS environment!"

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - dbaeumer.vscode-eslint # Add any other extensions you use
