image: gitpod/workspace-full # Pre-installed with AWS CLI, Docker, etc.
tasks:
  - name: Setup AWS
    init: |
      npm install  # Your project's install command
    command: |
      aws --version
      npm start
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode # AWS extension for Gitpod's VS Code interface
